### ISSUE TITLE
help ::  im having some dificulties with Route::context('photos', 'photo')  methods

### ISSUE THREAD

**Issue by ngangchill** [Patroklo/codeigniter-static-laravel-routes#4]
im having dificulties with Route::context('files', 'files');  methods. i have  a controller called files. it looks for a file in a directory/subdirectory,when it got the file it display the contents of the file in the browser..
it works file without this Route library. i work with  '_remap()' function. 

controller:

```
public function _render($file) {
       //got file name, 
        ....
        $this->view('files.index');
     }

public function _remap($method, $file = array()) {
    //.........
    .....
    return $this->_render($method . '/' . $file);
}
```

 urls:

 http://project.com/files         => it shows a default file.
 http://project.com/files/readme         => it shows readme.md file from the default folder
 http://project.com/files/book1/first         => it shows first.md file from the default folder/book1/first.md file

when i write the route like :    

```
   Route::context('files', 'files');       => it shows 404 error.

or 
 Route::context('files', 'files/index');       => it shows 404 error.
```

or if i  remove   _render(), and _remap() method and just keep index() function in the controller and define the route like Route::context('files', 'files/index');    it also shows  404 error
please help me..

**Comment by ngangchill** [comment]
Route::context('photos', 'photo');   showing 404 error... please help me...

**Comment by ngangchill** [comment]
or how can bypass this route class to use default ci routing!

**Comment by Patroklo** [comment]
Hi! I have back pain this days and can't sit down too much time, I'll try to see it around this days, dont worry

**Comment by Patroklo** [comment]
Ok, first of all, __remap() it's used by the library to use the filters, so, if you are going to use them in that controller, you should not extend the class or, at least, call it's parent class first (the core/My_Controller method) and then use your code.

About what you want to do, I think that it's calling from this url you have sent me for files, the problem it's that i had wrongly indented the context examples. As you see now, the $1 uri it's used before the "file". So, i think that you'll have to simply use optional parameters. 

For example

Route::any('files/{id1?}/{id3?}/{id2?}', 'files/index/$1/$2/$3');

Then you'll receive all the urls you have sent in the index method. 

http://project.com/files => won't give any uri, don't know exactly what you want here, maybe show all files in the directory?

http://project.com/files/readme => get "readme" as uri. So open "readme.md"
http://project.com/files/book1/first => get "book1" and "first" as uri.

SO, I have done an example:

Route::any('files/{id1?}/{id2?}/{id3?}/{id4?}', 'welcome/index/$1/$2/$3/$4');
$route = Route::map();

And called the url 

localhost/files/book1/readme

And used in the index model this code:

var_dump($this->uri->segment_array());

And the browser sends:

array(3) { [1]=> string(5) "files" [2]=> string(4) "book" [3]=> string(6) "readme" } 

Maybe this is what you need? There you have in order all the data you need, the only thing you have to check it's the array size to be able to see if there are directories or it's the main file.

Another option it's to use something like the context calling different methods, but without using context, because, as you have seen, the $1 goes first in the url. It's used for a different case.

Any doubt, If I haven't fully explained (english not my first language, it's spanish, and Im writting this fast because it hurts to be sitted XD ) please tell me.

**Comment by ngangchill** [comment]
thanks for your explanation..

http://project.com/files =>    shows a default file that contains all the links of present directory.

now i defined my route as

```
<?php
Route::any('learn', 'learn/load');
Route::any('learn/(:any)/(:any)/(:any)/(:any)/(:any)/(:any)',       'learn/index/$1/$2/$3/$4/$5/$6');
Route::any('learn/(:any)/(:any)/(:any)/(:any)/(:any)',      'learn/index/$1/$2/$3/$4/$5');
Route::any('learn/(:any)/(:any)/(:any)/(:any)',     'learn/index/$1/$2/$3/$4');
Route::any('learn/(:any)/(:any)/(:any)',        'learn/index/$1/$2/$3');
Route::any('learn/(:any)/(:any)',       'learn/index/$1/$2');
Route::any('learn/(:any)',      'learn/index/$1');
```

it works as aspected..

i will try as you say.

**Comment by ngangchill** [comment]
what about Route::context() method? it always showing 404 error!

i tried it with another controller but no luck.it shows error.

**Comment by ngangchill** [comment]
Route defined as  

```
      Route::any('files/{id1?}/{id2?}/{id3?}/{id4?}', 'learn/index/$1/$2/$3/$4');
```

url:    http://project.com/files       default url showing error because it passing   $1/$2/$3/$4  in the url that causing problem.
dump:  

```
    Dump => string(11) "$1/$2/$3/$4" 
```

url:    http://project.com/files/book1       works fine ... 
dump: 

```
   Dump => string(5) "book1"
```

**Comment by Patroklo** [comment]
Let me check that around this morning.

**Comment by Patroklo** [comment]
The context(), as i have said, will require you to use this kind of url:

http://urlblah/uri1/files/uri2/uri3...

As you see, uri1 MUST be first.

About the problem with the route

```
  Route::any('files/{id1?}/{id2?}/{id3?}/{id4?}', 'learn/index/$1/$2/$3/$4');
```

It works fine with my installation, maybe it could be a problem with:
- Controller doesn't have the first letter of its name in uppercase (file or class name)
- Not used a .htaccess to not to use the index.php/ in the url?

I have this htaccess:
RewriteEngine on

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

RewriteRule . index.php

What error appears? no file input? 404? I think that ill need more info to be able to help you in this situation, because if with uris the url works and without uris it doesn't it should be something that you and me have installed differently.

Is there a way that I could see your code to be sure everything's ok?

**Comment by ngangchill** [comment]
I have this htaccess:

RewriteEngine on 
RewriteRule ^$ /index.php [L] 
RewriteCond $1 !^(index.php|assets|user_guide|bootstrap|robots.txt|favicon.ico) 
RewriteRule ^(.*)$ /index.php/$1 [L]

**Comment by ngangchill** [comment]
Controller:  Learn.php

```
<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

 use Forhad\App\Md as M;
  use Forhad\App\ScanDir as D;

  class Learn extends MY_Controller {

      public $front_page = 'index';
      public $dir_default_file = 'index';

      public function __construct() {
          parent::__construct();
          $this->load->helper('file');
      }

  //    public function index() {
  //        dump('foo bar');
  //    }
      public function load($file) {
          //got file name, 
          $file = rtrim($file, '/');
         // dump_exit($file);
          //check front page or not  //for default frontpage system
          if ($file == 'index') {
              $file = ($file == $this->front_page) ? 'index' : $this->front_page; //modified    
          }
          if(!$file) $file = $this->front_page;
          if($file == '$1/$2/$3/$4') $file = $this->front_page;  // why??? 
          //lets get contents
          if(is_dir('content/'.$file)) $file =  $file.'/'.$this->dir_default_file;

          $this->data['content'] = M::parse($file);
          //category dept 1
          $this->data['categories'] = D::category('content/');
          //lets get meta data
          $meta = M::readFilemeta($file);
          //set metadata for da view file
          //$this->output->meta_from_array($meta);  // i have to work with this function
          $this->data['mymeta'] = (object) $meta;
          //set page title
          $this->data['title'] = $this->data['mymeta']->title;

          //all pages
          //$this->data['pages'] = M::getPages();       
          //get file
          $all_markdown_files = M::getFiles();
          foreach ($all_markdown_files as $key => $page) {
              // Skip 404
              if (basename($page) == '404.md') {
                  unset($all_markdown_files[$key]);
                  continue;
              }
              //cleaning up
              $url = str_replace('content/', '', str_replace('.md', '', $page));
              //make page url array for view & merge with pages array
              $url_array = array('page_url' => $url);
              //get all file metadata in a array
              $this->data['pages'][] = array_merge(M::readFilemeta($url), $url_array);
          }
          //all done,
          $this->v('learn.index');
      }

      public function _remap($method, $file = array()) {
          //dump_exit($file);

          $file = implode('/', $file);
         //dump_exit($file);
        //
          if (method_exists($this, $method)) {
              return $this->$method($file);
          }
          return $this->load($method . '/' . $file);
      }
```

**Comment by Patroklo** [comment]
Ok! That helped a lot! Checking it, solution should come in no time.

**Comment by Patroklo** [comment]
First of all, don't know why you are using _remap, this check you have there should be done in the route library, if Im not mistaken about you wanting to use "localhost.com/files/*" as a base route for getting files.

Second, if you are not going to use filters or the special features in the route library, you can extend your class from CI_Controller, because using remap method and extending from MY_Controller is basically breaking how the library works.

Third, you should use the uri class methods, like $this->uri->segment_array(); for example, or the uri class methods that I have done for the library, the parameters of the controller function don't work allways very well, I'll try to check if they fail because of my library, but, as i have said, i have used $this->uri->segment_array(); this method instead of the $file parameter and worked very well, really, try it and tell me.

**Comment by ngangchill** [comment]
before using ur Route Library ,i used _remap function for routing purpose  to get the files though url.

now i will remove _remap() function because your library makes routing more comfortable for me..i dont have much time today, i will do it tomorrow..
Thanks for the greate library..

**Comment by Patroklo** [comment]
I think you only have to change this

```
public function load() {
      //got file name, 
      $file = $this->uri->segment_array();
      unset($file[0]); // because it will send also the first uri, like "files"
```

Any problem, tell me. If it works, also tell me and I'll close the issue.

**Comment by ngangchill** [comment]
public function load() {
      //got file name, 
      $file = $this->uri->segment_array();
      unset($file[1]);  // first segment (files)  $file[1]

Thanks, it works fine...

**Comment by ngangchill** [comment]
you said: 

"The context(), as i have said, will require you to use this kind of url:

http://urlblah/uri1/files/uri2/uri3...

As you see, uri1 MUST be first."

why uri1 is at first?

i can not figure it out to make my url like as u said (e.g http://urlblah/uri1/files/uri2/uri3)  

Thanks for your help..

**Comment by Patroklo** [comment]
This kind of routes are usually used for CRUD purposes, like:

localhost.com/john/edit/
localhost.com/john/update/password

etc...

**Comment by ngangchill** [comment]
thanks..

greate library ever i used with CI...  :+1:
